language: java
jdk:
  - openjdk15

branches:
  only:
    - master # master 브랜치에 push되었을 때만 동작

# Travis CI 서버의 Home
cache: # gradle을 통해 받은 의존성들을 캐시에 저장하여 같은 의존성은 다음 배포 때 다시 받지 않는다.
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew # build 시 gradle 권한 부여

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - hsro2228@naver.com

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: chatting-deploy # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: https://github.com/hwangsero/socket.git #Github 주소
      branch: master