spring:
  profiles:
    active: local
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl


#spring:
#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: false
#  freemarker:
#    cache: false


